/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AlturaNFTPasss__factory } from "./AlturaNFTPasss__factory";
export { Counter__factory } from "./Counter__factory";
